config/routes.rb
MockStubDemo::Application.routes.draw do
  root to: 'banks#index'
  resources :banks
  resources :users

end

app/models/bank.rb
class Bank < ActiveRecord::Base
  
  has_many :bank_user_associations
  has_many :users, through: :bank_user_associations
end

app/models/bank_user_association.rb
class BankUserAssociation < ActiveRecord::Base
  belongs_to :user
  belongs_to :bank  
end

app/models/transaction.rb
class Transaction

  # The fact that this class never hits the database makes it a perfect scenario
  # for using mock and stub tests.
  
  def initialize(user, bank)
    @user = user
    @bank = bank
  end

  def afford_loan?
    @user && @user.account_money > 0
  end
  
  def has_user?
    @user.present?  
  end
  
  def has_bank?
    @bank.present?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :last_name
  validates_length_of :name, maximum: 50
  
  has_one :bank_user_association
  has_one :bank, through: :bank_user_associations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /banks/1
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /banks/1
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h5>Editing Bank</h5></div>
  <div class="row edit-form">
    <div class="col-md-4">
      <%= render 'form' %>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <%= link_to 'Show', @bank,:class => "btn btn-link" %> |
  <%= link_to 'Back', banks_path,:class => "btn btn-link" %>
</div>

app/views/banks/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h5>Listing Banks</h5>
    <%= link_to 'New Bank', new_bank_path, class: 'btn btn-primary btn-sm pull-right', role: 'button' %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      <% @banks.each do |bank| %>
        <tr>
          <td><%= bank.name %></td>
          <td><%= link_to 'Show', bank, class: 'btn btn-link' %></td>
          <td><%= link_to 'Edit', edit_bank_path(bank), class: 'btn btn-link' %></td>
          <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/banks/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h5>New Bank</h5></div>
  <div class="row edit-form">
    <div class="col-md-4">
      <%= render 'form' %>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <%= link_to 'Back', banks_path,:class => "btn btn-link" %>
</div>

app/views/banks/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><h5><%= @bank.name %> Details</h5></div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @bank.name %></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_bank_path(@bank),:class => "btn btn-link" %> |
  <%= link_to 'Back', banks_path,:class => "btn btn-link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MockStubDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :account_money %><br>
    <%= f.text_field :account_money, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h5>Editing user</h5></div>
  <div class="row edit-form">
    <div class="col-md-4">
      <%= render 'form' %>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <%= link_to 'Show', @user,:class => "btn btn-link" %> |
  <%= link_to 'Back', users_path,:class => "btn btn-link" %>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h5>Listing Users</h5>
    <%= link_to 'New User', new_user_path, class: 'btn btn-primary btn-sm pull-right', role: 'button' %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Last Name</th>
        <th>Account Money</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.account_money %></td>
          <td><%= link_to 'Show', user, class: 'btn btn-link' %></td>
          <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-link' %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h5>New User</h5></div>
  <div class="row edit-form">
    <div class="col-md-4">
      <%= render 'form' %>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <%= link_to 'Back', users_path,:class => "btn btn-link" %>
</div>

app/views/users/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><h5><%= @user.name %> Details</h5></div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Last Name</th>
        <th>Account Money</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.name %></td>
        <td><%= @user.last_name %></td>
        <td><%= @user.account_money %></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Edit', edit_user_path(@user),:class => "btn btn-link" %> |
  <%= link_to 'Back', users_path,:class => "btn btn-link" %>
</div>